### ISSUE TITLE
Bad filepath error (No such file or directory)

### ISSUE THREAD

**Issue by EmreDogann** [gennaro-tedesco/nvim-possession#24] opened 2023-06-12 18:23 UTC
I created the sessions/ directory and used the default binding \<leader>sn to create a new session. However, when I go to load that same session file from the session list (\<leader>sl) then I get this error:
![image](https://github.com/gennaro-tedesco/nvim-possession/assets/48212096/72942c45-3a23-4cac-a358-6c1399c0b655)

It looks like to me that there is some junk characters at the beginning of entry_str messing up the file path.
They are not regular whitespace it seems as a vim.trim(entry_str) did not work.
If I strip the beginning characters via a substring, it works fine with no errors:
![image](https://github.com/gennaro-tedesco/nvim-possession/assets/48212096/bb918c1b-3e88-49a7-9a81-fe4bcc58f020)

Why is there whitespace at the start of entry_str?

EDIT:
I just noticed that my possession.list() window looks very different from the list menu in the README gif. Maybe a change with fzf?

### Versions
fzf-lua: Main branch, commit [2670983](https://github.com/ibhagwan/fzf-lua/tree/267098387dd7a3c53f8a4cfb17285ba05d841353) (most recent version as of posting)
nvim-possession: Main branch, commit [27f7535](https://github.com/gennaro-tedesco/nvim-possession/tree/27f7535a584fac2cc3b124f090ae4f26f4f338bf) (most recent version as of posting)

NVIM v0.9.2-dev-25+g470017c9a
Build type: Release (Built from source)
Using lazy.nvim

**Comment by gennaro-tedesco** [comment] 2023-06-13 01:58
Let us try and understand under what circumstances the error can be reproduced:

> I created the sessions/ directory 

does this mean the error occurs when setting a custom 
```lua
sessions = {
  sessions_path =
```
rather than `vim.fn.stdpath("data") .. "/sessions/" ` or do you still see the error with default configuration? Moreover I see that in your example you are explicitly setting a `fzf-lua` previewer: would it still occur if using the default configuration for both `nvim-possession` and `fzf-lua`, namely just using
```lua
{
  "gennaro-tedesco/nvim-possession",   
  dependencies = {
     "ibhagwan/fzf-lua",
  },
  config = true,
```
? I am running the default configuration with latest commits as of now and cannot reproduce it.

**Comment by EmreDogann** [comment] 2023-06-13 09:18
So I've stripped everything down to the code snippet you provided and unfortunately, it's the same error.
I also uninstalled all my other plugins in case of conflicts but that didn't help.

**Comment by gennaro-tedesco** [comment] 2023-06-13 09:53
So if I understand correctly: 

1. you created the session folder manually on your computer
2. you indicated the path to said session folder in ```lua sessions = {
  sessions_path = ...
  ...
}```
3. though the path is correct, you see an exception `"No such file or directory"`
4. such exception in 3. occurs because of extra white spaces that aren't stripped correctly
5. if you use the `fzf-lua` setup "Telescope" the error disappears

is the summary correct (just for me to understand)?

What is your `fzf-lua` setup? I cannot reproduce the error by using a default `fzf-lua` configuration, so I suspect there may be some previewers options that you may be setting that for some reasons artificially add the extra spaces (and they happen to disappear when using the "Telescope" setup). In particular the plugin uses the in-built previewer, so do not manually set `bat` as one.

P. S. Do you maybe have some particular `fzf` options, for separators, inline arguments or such? `fzf-lua` inherits the general `fzf` shell options and parses them into the preview, so that may cause some additional characters to appear.

**Comment by EmreDogann** [comment] 2023-06-13 10:23
> you created the session folder manually on your computer
you indicated the path to said session folder in

I created the folder manually in the default location (i.e. `vim.fn.stdpath("data") .. "/sessions/"`). I did not change the `sessions_path` field.

> What is your fzf-lua setup?

My setup is the default, in this case it is loading fzf-lua as a dependency through nvim-possession.

> P. S. Do you maybe have some particular fzf options, for separators, inline arguments or such? fzf-lua inherits the general fzf shell options and parses them into the preview, so that may cause some additional characters to appear.

I do have a `.zshrc` where I set some fzf arguments like separators and such, but I've commented those out and reloaded to make sure they weren't conflicting. Maybe there is some cache somewhere that fzf might be using?

**Comment by gennaro-tedesco** [comment] 2023-06-13 10:51
Could you show me (perhaps with a small recording) the following steps:

1. create a new session with `nvim-possession`
2. go to the location of said session on your computer, check if the name/path is correct
3. load the session (which should allegedly result in an error)

What are the characters `~/.d/l/s/n/s/` that are displayed in your screenshot, at the `fzf-lua` prompt? Might it be they are references to other directories and perhaps something on your computer isn't resolving the `~/` correctly?

**Comment by EmreDogann** [comment] 2023-06-13 11:48
> What are the characters ~/.d/l/s/n/s/

This is the short path to my `vim.fn.stdpath("data")` folder which in my case is `~/.dotfiles/local/share/nvim/`. To be honest I don't know why fzf is showing it as this short path I don't recall settings anything like that.
It follows what I set for my XDG paths:

```Cpp
# Inside .zshenv
export XDG_CONFIG_HOME = $HOME/.dotfiles
export XDG_DATA_HOME = $XDG_CONFIG_HOME/local/share
export XDG_CACHE_HOME = $XDG_CONFIG_HOME/cache
``` 

What I did was clear my `vim.fn.stdpath("data")` folder and tried it again. But when I now go to call `require('nvim-possession').new()` I get a different error:

https://github.com/gennaro-tedesco/nvim-possession/assets/48212096/46e906eb-b118-4e85-b443-9398b60cc5a8

**Comment by gennaro-tedesco** [comment] 2023-06-13 12:24
Hmm, may I ask what operating system you are on? I have repeated all your steps above and I could not reproduce the exception, so I am led to believe that the extra spaces you see may be a representation of the `fzf` prompt that is specific to your machine. In particular you can see from your recording above that, when `nvim-possession` saves the session, the path is correctly indicated to be exactly the location where the session exists (with no extra spaces). The exception occurs when the [entry string](https://github.com/gennaro-tedesco/nvim-possession/blob/main/lua/nvim-possession/ui.lua#L18) is fed via the [fzf-prompt](https://github.com/gennaro-tedesco/nvim-possession/blob/27f7535a584fac2cc3b124f090ae4f26f4f338bf/lua/nvim-possession/init.lua#L125-L132).

What happens when you just invoke `fzf` (either `fzf-lua` per sé in neovim or `fzf` in the terminal)? My guess is that you would see the additional extra spaces there as well.

**Comment by EmreDogann** [comment] 2023-06-13 12:50
> Hmm, may I ask what operating system you are on?

I'm on Windows 11 using WSL 2 Ubuntu via Windows Terminal.

Invoking `fzf` in the terminal seems to be working fine:
![image](https://github.com/gennaro-tedesco/nvim-possession/assets/48212096/40b0e60b-2136-4482-ae68-12983341d050)

Invoking it in nvim using `:lua require('fzf-lua').files({cwd = '~/.dotfiles', cmd = "fd --no-ignore --hidden"})` seems to be fine as well:
![image](https://github.com/gennaro-tedesco/nvim-possession/assets/48212096/e0e40144-784e-436c-98b6-3b8a5fc0e5e5)

**Comment by gennaro-tedesco** [comment] 2023-06-13 13:01
> Invoking it in nvim using

isn't there an additional white space between the icon and the first character of your first entry (` local`)? Anyway: I didn't try on Windows (as I don't have a Windows computer at hand), only on MacOs and Linux. 

I will continue investigating, but unless I come across a Windows computer I cannot guarantee to resolve this quickly, unfortunately; apologies for that, I _am_ trying to reproduce it but it just doesn't manifest on my machines. As a workaround you could use the "Telescope" setup (what of it didn't convince you?), in the meantime I will try to ask the maintainer of `fzf-lua` to see if he is aware of a specific Windows behaviour that prompts extra white spaces.

**Comment by gennaro-tedesco** [comment] 2023-06-13 13:05
Sorry that we couldn't resolve this yet - I will keep the issue open and keep you updated as well!

**Comment by EmreDogann** [comment] 2023-06-13 13:18
Update:

I think your hunch about the white and icons might be correct. I just tested it out with some of the other presets:

https://github.com/gennaro-tedesco/nvim-possession/assets/48212096/29f0e054-c062-45e6-9143-cbb0d198a09c

It seems that "telescope" and "max-perf" presets work fine.

Looking at the fzf-lua README it seems that the icons might be the issue here:
![image](https://github.com/gennaro-tedesco/nvim-possession/assets/48212096/e5b4caae-00cb-41c1-bd47-3abb2ba3f25e)

**Comment by gennaro-tedesco** [comment] 2023-06-13 13:35
Ah, so probably both `max-perf` and `telescope` silently remove the space allocated to devicons, whereas the other defaults force a white space when [icons are explicitly removed](https://github.com/gennaro-tedesco/nvim-possession/blob/27f7535a584fac2cc3b124f090ae4f26f4f338bf/lua/nvim-possession/init.lua#L128)!

I would still expect it to work if you choose any other preset _but_ manually set icons to `false` in your `fzf-lua` setup configuration. This said, great that we could make it work at the end!

**Comment by EmreDogann** [comment] 2023-06-13 13:39
So it's not only `file_icons` in fzf-lua but also `git_icons`. Once i set those both to false in the fzf-lua config, it seems to work.
With that being said, is there no way to set file and git icons to false only in nvim-possesion windows? It would be nice to have to option to display these icons in other windows.

**Comment by gennaro-tedesco** [comment] 2023-06-13 13:47
> With that being said, is there no way to set file and git icons to false only in nvim-possesion windows? 

I do have such setup, have a look [here](https://github.com/gennaro-tedesco/dotfiles/blob/fac26bbc78f71ef2fe0cd08c8abc933d52708da6/nvim/lua/plugins/fzf.lua#L22): essentially you have to explicitly enable the git/file icons for the pickers you want instead of using presets; `nvim-possession` sets icons to false automatically, so you wouldn't have problems there. I presume that by using presets they somehow take over whatever other `fzf-lua` prompt there is, which is the reason why we saw those extra spaces in your example, and this shouldn't happen if you just configure the single pickers by themselves.

If you use (modifying at your will) my dotfiles that I link above you will exactly reproduce the setup as in the README :)

**Comment by EmreDogann** [comment] 2023-06-13 13:48
Ok so modifying `M.list()` inside `nvim-possession/init.lua' to also disable `git_icons` like so:
```lua
---list all existing sessions and their files
	---return fzf picker
	M.list = function()
		local iter = vim.loop.fs_scandir(user_config.sessions.sessions_path)
		if iter == nil then
			print("session folder " .. user_config.sessions.sessions_path .. " does not exist")
			return
		end
		local next = vim.loop.fs_scandir_next(iter)
		if next == nil then
			print("no saved sessions")
			return
		end

		return fzf.files({
			user_config = user_config,
			prompt = user_config.sessions.sessions_icon .. "sessions:",
			file_icons = false,
			git_icons = false,		<-------- Adding this fixed the issue
			show_cwd_header = false,
			preview_opts = "nohidden",

			previewer = ui.session_previewer,
			winopts = user_config.fzf_winopts,
			cwd = user_config.sessions.sessions_path,
			actions = {
				["default"] = M.load,
				["ctrl-x"] = { M.delete_selected, fzf.actions.resume },
			},
		})
	end
``` 

Fixes the issue for me, wihtout having to disable any icons in my fzf-lua config.

**Comment by gennaro-tedesco** [comment] 2023-06-13 13:50
...what if you open a PR with that fix, so that I can include it and we fix this once and for all? :)

**Comment by EmreDogann** [comment] 2023-06-13 13:51
Sure thing!

**Closed** 2023-06-13 15:25 UTC

**Comment by gennaro-tedesco** [comment] 2023-06-13 15:34
> By the way, it would be nice if you linked the config to get nvim-possession looking like the gif in the README. I was a bit confused at first because my one looked vastly different.

Do you mean the configuration to be found in my dotfiles?

**Comment by EmreDogann** [comment] 2023-06-13 15:35
Yeah that could work

**Comment by gennaro-tedesco** [comment] 2023-06-13 15:35
That is a good idea: I will try to clean it up a little and link the relevant bits! :)
